import HEART_SELECTD from "../assets/images/heart_selected_ic.svg";
import HOME_IC from "../assets/images/home_ic.svg";
import HEART_IC from "../assets/images/heart_ic.svg";
import HEART_TRANSPARENT from "../assets/images/heart_transparent.svg";
import HEART_SELECTED_SMALL from "../assets/images/heart_selected_small.svg";

import CART_IC from "../assets/images/cart_ic.svg";
import ACCOUNT_IC from "../assets/images/account_ic.svg";
import MARKET_IC from "../assets/images/market_ic.svg";
import MARKET_SELECTED from "../assets/images/market_selected.svg";
import HOME_SELECTED from "../assets/images/home_selected.svg";
import CART_SELECTED from "../assets/images/cart_selected.svg";
import ACCOUNT_SELECTED from "../assets/images/account_selected.svg";

export default appImages = {
  back: require("../assets/images/back.png"),
  eye: require("../assets/images/eye.png"),
  close: require("../assets/images/close.png"),
  full_eye: require("../assets/images/full_eye.png"),
  forgot_reset: require("../assets/images/forgot_reset.png"),
  right_arrow: require("../assets/images/right_arrow.png"),
  cart_ic: require("../assets/images/cart_ic.png"),
  heart_ic: require("../assets/images/heart_ic.png"),
  cart_selected_ic: require("../assets/images/cart_selected_ic.png"),
  black_back_ic: require("../assets/images/black_back_ic.png"),
  email_ic: require("../assets/images/email_ic.png"),
  phone_ic: require("../assets/images/phone_ic.png"),
  master_card_ic: require("../assets/images/master_card_ic.png"),
  visa_ic: require("../assets/images/visa_ic.png"),
  delete_ic: require("../assets/images/delete_ic.png"),
  card_shape_ic: require("../assets/images/card_shape_ic.png"),
  express_ic: require("../assets/images/express_ic.png"),
  question_ic: require("../assets/images/question_ic.png"),
  question_ic_black: require("../assets/images/question_ic_black.png"),
  offer_image: require("../assets/images/offer_image.png"),
  chat_ic: require("../assets/images/chat_ic.png"),
  search_ic: require("../assets/images/search_ic.png"),
  location_ic: require("../assets/images/location_ic.png"),
  location_pin_ic: require("../assets/images/location_pin_ic.png"),
  large_location_pin: require("../assets/images/large_location_pin.png"),
  small_chat_ic: require("../assets/images/small_chat_ic.png"),
  prepaid_ic: require("../assets/images/prepaid_ic.png"),
  care_ic: require("../assets/images/care_ic.png"),
  large_cart_ic: require("../assets/images/large_cart_ic.png"),
  meals_ic: require("../assets/images/meals_ic.png"),
  savage_man_img: require("../assets/images/savage_man_img.png"),
  warrior_man_img: require("../assets/images/warrior_man_img.png"),
  chieftain_man_img: require("../assets/images/chieftain_man_img.png"),
  paypal_logo: require("../assets/images/paypal_logo.png"),
  small_qrcode_ic: require("../assets/images/small_qrcode_ic.png"),
  processing_img: require("../assets/images/processing_img.png"),
  cock_ic: require("../assets/images/cock_ic.png"),
  del_searchch_ic: require("../assets/images/del_searchch_ic.png"),
  tick_ic: require("../assets/images/tick_ic.png"),
  white_tick: require("../assets/images/white_tick.png"),
  support_img: require("../assets/images/support_img.png"),
  chat_send_ic: require("../assets/images/chat_send_ic.png"),
  chat_file_ic: require("../assets/images/chat_file_ic.png"),
  overlay_img: require("../assets/images/overlay_img.png"),
  search_large_ic: require("../assets/images/search_large_ic.png"),
  calander_ic: require("../assets/images/calander_ic.png"),
  add_fav_btn_ic: require("../assets/images/add_fav_btn_ic.png"),
  heart_selected_ic: require("../assets/images/heart_selected_ic.png"),
  not_available_ic: require("../assets/images/not_available_ic.png"),
  bell_ic: require("../assets/images/bell_ic.png"),
  plus_ic: require("../assets/images/plus_ic.png"),
  plus_white_ic: require("../assets/images/plus_white_ic.png"),
  minus_white_ic: require("../assets/images/minus_white_ic.png"),
  clock_ic: require("../assets/images/clock_ic.png"),
  friend_man_img: require("../assets/images/friend_man_img.png"),
  red_calander_ic: require("../assets/images/red_calander_ic.png"),
  circle_animation: require("../assets/images/circle_animation.gif"),
  instore_ic: require("../assets/images/instore_ic.png"),
  thick_arrow: require("../assets/images/thick_arrow.png"),
  red_location_ic: require("../assets/images/red_location_ic.png"),
  wallet_red_ic: require("../assets/images/wallet_red_ic.png"),
  dotted_line: require("../assets/images/dotted_line.png"),
  caveman_error: require("../assets/images/caveman_error.png"),
  trash: require("../assets/images/Trash.png"),

  last_order_ic: require("../assets/images/last_order_ic.png"),
  shop_category_ic: require("../assets/images/shop_category_ic.png"),
  specials_ic: require("../assets/images/specials_ic.png"),
  home_food_img: require("../assets/images/home_food_img.png"),
  vertical_overlay: require("../assets/images/vertical_overlay.png"),
  promise1: require("../assets/images/promise1.png"),
  promise2: require("../assets/images/promise2.png"),
  promise3: require("../assets/images/promise3.png"),
  promise4: require("../assets/images/promise4.png"),
  qr_coe_img: require("../assets/images/qr_coe_img.png"),
  thai_payment_img: require("../assets/images/thai_payment_img.png"),
  banks_img: require("../assets/images/banks_img.png"),
  thik_search_ic: require("../assets/images/thik_search_ic.png"),
  fresh_meals_ic: require("../assets/images/fresh_meals_ic.png"),
  split_img: require("../assets/images/split_img.png"),
  heart_ic_transparent: require("../assets/images/heart_ic_transparent.png"),
  small_bell_ic: require("../assets/images/small_bell_ic.png"),

  white_circle: require("../assets/images/white_circle.png"),
  location_black_ic: require("../assets/images/location_black_ic.png"),
  address_phone_ic: require("../assets/images/address_phone_ic.png"),
  empty_cart: require("../assets/images/empty-cart.png"),
  mto: require("../assets/images/mto.png"),
  mtoWhite: require("../assets/images/mto-white.png"),
  postcode_bg: require("../assets/images/postcode_bg.png"),

  qrcode1: require("../assets/images/qrcode1.png"),
  qrcode2: require("../assets/images/qrcode2.png"),
  qrcode3: require("../assets/images/qrcode3.png"),
  qrcode4: require("../assets/images/qrcode4.png"),
  qrcode5: require("../assets/images/qrcode5.png"),

  byo_plate: require("../assets/images/byo_plate.png"),
  byo_salad: require("../assets/images/byo_salad.png"),

  //svg
  HEART_SELECTD,
  HOME_IC,
  HEART_IC,
  CART_IC,
  ACCOUNT_IC,
  MARKET_IC,
  MARKET_SELECTED,
  HOME_SELECTED,
  CART_SELECTED,
  ACCOUNT_SELECTED,
  HEART_TRANSPARENT,
  HEART_SELECTED_SMALL,

  whiteLogo: require("../assets/images/white-logo.png"),
  welcome1: require("../assets/images/welcome/welcome1.png"),
  welcomeOverlay1: require("../assets/images/welcome/welcome-overlay1.png"),
  welcome2: require("../assets/images/welcome/welcome2.png"),
  welcomeOverlay2: require("../assets/images/welcome/welcome-overlay2.png"),
  welcome3: require("../assets/images/welcome/welcome3.png"),
  welcomeOverlay3: require("../assets/images/welcome/welcome-overlay3.png"),
  welcomeTextBackground: require("../assets/images/welcome/welcome-texts-background.png"),

  aboutUs1: require("../assets/images/aboutus/about-us-1.png"),
  aboutUs2: require("../assets/images/aboutus/about-us-2.png"),
  aboutUs3: require("../assets/images/aboutus/about-us-3.png"),
  aboutUs4: require("../assets/images/aboutus/about-us-4.png"),

  aboutUsMission: require("../assets/images/aboutus/mission.png"),

  aboutUsPromise1: require("../assets/images/aboutus/promise_1.png"),
  aboutUsPromise2: require("../assets/images/aboutus/promise_2.png"),
  aboutUsPromise3: require("../assets/images/aboutus/promise_3.png"),
  aboutUsPromise4: require("../assets/images/aboutus/promise_4.png"),
  aboutUsPromise5: require("../assets/images/aboutus/promise_5.png"),

  aboutUsNoThanks: require("../assets/images/aboutus/no_thanks.png"),

  aboutUsInstagram: require("../assets/images/aboutus/instagram.png"),
  aboutUsLine: require("../assets/images/aboutus/line.png"),
  aboutUsBlog: require("../assets/images/aboutus/blog.png"),

  deliveryMap: require("../assets/images/deliverydetails/map.png"),

  dashedLine: require("../assets/images/dashed-line.png"),
  downArrow: require("../assets/images/down-arrow.png"),

  // app updates
  splashLogo: require("../assets/images/splash-logo.png"),

  cautionDangerIcon: require("../assets/images/caution_danger_ic.png"),
  appTrackingPageLogo: require("../assets/images/logo-apptracking.png"),

  iconSwipteHandGesture: require("../assets/images/icon-swipe-hand-gesture.png"),
  friend: require("../assets/images/sample/friend.png"),
  overlay: require("../assets/images/sample/overlay.png"),
  commentIcon: require("../assets/images/comment.png"),
  upArrow: require("../assets/images/up_arrow.png"),
  downArrow: require("../assets/images/down_arrow.png"),
  lineIcon: require("../assets/images/line/icon.png"),
  lineIconDisabled: require("../assets/images/line/icon_disabled.png"),
  lineOfficialAccountIcon: require("../assets/images/line/icon_line_official_account.png"),
  iconInfo: require("../assets/images/icon-info.png"),
  buttonFolowLINEQA: require("../assets/images/line/icon-follow-line-qa.png"),
  logoSurvey: require("../assets/images/logo_survey.png"),
  success_ic: require("../assets/images/success_ic.png"),
  logoThanks: require("../assets/images/logo_thanks.png"),
  logoGoogle: require("../assets/images/logo_google.png"),
  logoFacebook: require("../assets/images/logo_facebook.png"),
  logoAppstore: require("../assets/images/logo_appstore.png"),
  goto_ic: require("../assets/images/goto_ic.png"),

  expand: require("../assets/images/expand.png"),
  collapse: require("../assets/images/collapse.png"),
  emoticon: require("../assets/images/emoticon.png"),
  emoticon_1: require("../assets/images/emoticon_1.png"),
  emoticon_2: require("../assets/images/emoticon_2_3.png"),
  emoticon_3: require("../assets/images/emoticon_3.png"),
  emoticon_4: require("../assets/images/emoticon_4.png"),

  notified: require("../assets/images/notified.png"),
};
